### ISSUE TITLE
Gutenberg causes post publish to happen earlier

### ISSUE THREAD

**Issue by joedolson** [joedolson/wp-to-twitter#1]
Will need to rewrite trigger process so that tags & other data are already saved. Will also resolve issues with RSS feed importers that mis-order operations, but now it's a core problem.

**Comment by rob006** [comment]
@joedolson Any progress with this task? Is the WP Tweets Pro also affected by this bug? We recently switched to new block editor and every day we're getting tweets with invalid category (included in URL) and thumbnail.

**Comment by joedolson** [comment]
No, no real progress. I was hoping that Gutenberg would fix the problem, but...that's not going to happen, I think. I'm not totally sure what I'm going to do for the rewrite; it'll be a pretty significant change. It does impact WP Tweets Pro, as well. 

As long as you always save a draft with all metadata (categories, tags, images, etc.) added before publishing, you should be OK.

**Comment by rob006** [comment]
> It does impact WP Tweets Pro, as well.

Oh, that is surprising - I thought that enabling delayed tweets will help here. :/

**Comment by joedolson** [comment]
It effects the creation of the Tweet text - and WP to Twitter generates that text at publication, and schedules the Tweets using the text generated from the template. One of the changes necessary to make this work (for Pro) is to change it to only generate the Tweet itself at the scheduled time - which is a change that has a deep-reaching impact within the plug-in.

**Comment by joedolson** [comment]
Resolved in https://github.com/joedolson/wp-to-twitter/commit/ef4cfaa0ba393d41d1440ff2aaea55d6c7da36b0
